databases:
  - name: getsocial-db
    databaseName: getsocial
    user: nexus_user
    plan: free

services:
  - type: redis
    name: getsocial-redis
    plan: free
    ipAllowList: []

  - type: web
    name: getsocial-web
    runtime: docker
    plan: free
    dockerContext: backend
    dockerfilePath: backend/Dockerfile
    dockerCommand: daphne -b 0.0.0.0 -p $PORT config.asgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: getsocial-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: getsocial-redis
          property: connectionString
