apiVersion: v1
kind: ConfigMap
metadata:
  name: getsocial-config
data:
  DEBUG: "False"
  DJANGO_ALLOWED_HOSTS: "*"
  DATABASE_URL: "postgres://nexus_user:nexus_password@postgres:5432/nexus_db" # Update with real DB URL
  REDIS_URL: "redis://redis:6379/0"
  CELERY_BROKER_URL: "redis://redis:6379/0"
